/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-11 09:55:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.admin.product.model.vo.Attachment;
import com.kh.admin.product.model.vo.BookMaster;
import java.util.ArrayList;
import com.kh.member.model.vo.Member;

public final class mainpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/main/../common/search_head.jsp", Long.valueOf(1639216530003L));
    _jspx_dependants.put("/views/main/../common/main_end.jsp", Long.valueOf(1638543132000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.admin.product.model.vo.BookMaster");
    _jspx_imports_classes.add("com.kh.admin.product.model.vo.Attachment");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	ArrayList<BookMaster> bmlist = (ArrayList<BookMaster>)request.getAttribute("bmlist");
	ArrayList<BookMaster> bmNewlist = (ArrayList<BookMaster>)request.getAttribute("bmNewlist");
	String category = (String)request.getAttribute("category");
	String sort = (String)request.getAttribute("sort");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
	
	String contextPath = request.getContextPath(); // /jsp
	Member loginUser = (Member)session.getAttribute("loginUser");
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("    <!-- Bootstrap icons-->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("    <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        div, form {\r\n");
      out.write("            box-sizing : border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 전체를 감싸는 div */\r\n");
      out.write("        #header_2 {\r\n");
      out.write("            width : 600px;\r\n");
      out.write("            height : 250px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin-left: 25%;\r\n");
      out.write("        }\r\n");
      out.write("        /* 검색창 form에 대해서 속성 */\r\n");
      out.write("        #search_form {\r\n");
      out.write("            width : 80%;\r\n");
      out.write("            height: 20%;\r\n");
      out.write("            margin : auto;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 0px;\r\n");
      out.write("            left : 0px;\r\n");
      out.write("            bottom: 0px;\r\n");
      out.write("            top : 0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 검색창 form 내부의 div 속성 */\r\n");
      out.write("        #search_form>div {\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            float : left;\r\n");
      out.write("        }\r\n");
      out.write("        #search_text {\r\n");
      out.write("            width : 80%;\r\n");
      out.write("        }\r\n");
      out.write("        #search_btn {\r\n");
      out.write("            width : 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* input 태그들 늘려주기 */\r\n");
      out.write("        #search_form input {\r\n");
      out.write("            width : 100%;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #search_form button {\r\n");
      out.write("            width : 100%;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print(contextPath);
      out.write("\">북적북적</a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                     <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(contextPath);
      out.write("\">Home</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(contextPath);
      out.write("/PwdForm.me\">MyPage</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/faqForm.fa\">고객센터</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/noticeList.ad\">공지사항</a></li>\r\n");
      out.write("                 \r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Category</a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=1\">소설</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=2\">에세이</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=3\">역사</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=4\">과학</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=5\">정치</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=6\">로맨틱</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form class=\"d-flex\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/list.ba\" class=\"btn btn-outline-light\" type=\"submit\">\r\n");
      out.write("                    <i class=\"bi-cart-fill me-1\"></i>\r\n");
      out.write("                    Cart\r\n");
      out.write("                    <span class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\r\n");
      out.write("                </a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                \r\n");
      out.write("              ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("                <!-- 로그인 전 -->\r\n");
      out.write("                \r\n");
      out.write("	                <button class=\"btn btn-outline-light\" type=\"button\" onclick =\"location.href = '");
      out.print( contextPath );
      out.write("/loginForm.me'\">\r\n");
      out.write("	                   \r\n");
      out.write("	                    Login\r\n");
      out.write("	                </button>\r\n");
      out.write("	            <!-- 로그인 후 -->\r\n");
      out.write("	            ");
 } else { 
      out.write("\r\n");
      out.write("	            	<button class=\"btn btn-outline-light\" type=\"button\" onclick =\"location.href = '");
      out.print( contextPath );
      out.write("/logout.me'\">\r\n");
      out.write("	                  \r\n");
      out.write("	                    Logout\r\n");
      out.write("	                </button>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	            	 <button style=\"color:withe;\" class=\"btn btn-outline-light\" type=\"button\">\r\n");
      out.write("	                    ");
      out.print(loginUser.getUserName() );
      out.write("회원님 환영합니다.\r\n");
      out.write("	                </button>\r\n");
      out.write("	            ");
 } 
      out.write("\r\n");
      out.write("	         \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Header-->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("            <div class=\"text-center text-white\">\r\n");
      out.write("                <div class=\"container\"> \r\n");
      out.write("                    <a href=\"");
      out.print( contextPath);
      out.write("/main.mi\"><img src=\"/semi/resources/logo.png\" title=\"로고\" ></a>\r\n");
      out.write("                    <div id=\"header_2\">\r\n");
      out.write("                        <form id=\"search_form\">\r\n");
      out.write("                            <div id=\"search_text\">\r\n");
      out.write("                                <input type=\"search\" id=\"keyword\" name=\"keyword\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"search_btn\">\r\n");
      out.write("                                <button class=\"btn btn-dark btn-block\" type=\"button\" style=\"padding: 0px;\" onclick=\"bookSearch('keyword','','title');\">검색</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         <script>\r\n");
      out.write("        	var obj = {};\r\n");
      out.write("        	function bookSearch(type,category,sort) {\r\n");
      out.write("        		//ajax \r\n");
      out.write("        		if(type != '') {\r\n");
      out.write("        			if(type == \"keyword\"){\r\n");
      out.write("        				obj.type = \"keyword\";\r\n");
      out.write("        				obj.keyword = $(\"#keyword\").val();\r\n");
      out.write("\r\n");
      out.write("            		}\r\n");
      out.write("            		else if(type == \"new\"){\r\n");
      out.write("            			obj.type = \"new\";\r\n");
      out.write("\r\n");
      out.write("            		}\r\n");
      out.write("            		else if(type == \"best\"){\r\n");
      out.write("            			obj.type = \"best\";\r\n");
      out.write("\r\n");
      out.write("            		}\r\n");
      out.write("            		else{\r\n");
      out.write("            			obj.type = \"category\";\r\n");
      out.write("            			obj.category = category;\r\n");
      out.write("            		}\r\n");
      out.write("        		}\r\n");
      out.write("        		obj.sort = sort;\r\n");
      out.write("\r\n");
      out.write("        		$.ajax ({\r\n");
      out.write("        			\r\n");
      out.write("        			url : \"productSearch.mi\",\r\n");
      out.write("        			\r\n");
      out.write("        			data : obj,\r\n");
      out.write("        			\r\n");
      out.write("					success : function(list) {\r\n");
      out.write("						\r\n");
      out.write("						$(\"#mainSection\").hide();\r\n");
      out.write("		        		\r\n");
      out.write("						$(\"#searchResult\").show();\r\n");
      out.write("					\r\n");
      out.write("						var result = \"\";\r\n");
      out.write("                        \r\n");
      out.write("                    \r\n");
      out.write("						if(list.length != 0) {\r\n");
      out.write("							\r\n");
      out.write("							for(var i in list) { // for in\r\n");
      out.write("								\r\n");
      out.write("								result += \"<tr>\"\r\n");
      out.write("						                      + \"<td style='width:16%;'><a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=\"+list[i].bookNo +\"'><img src='");
      out.print( contextPath );
      out.write("/\" + list[i].filePath + list[i].changeName + \"' style='width:80%;'></td></a>\"\r\n");
      out.write("						                      + \"<td class='title' style='padding-top:8%;'><div>\"+list[i].title +\"</div><span style='font-size:0.7em;'>\"+list[i].author +\" | \"+list[i].publisher +\" | \"+list[i].pblctDate +\"</span></td>\"\r\n");
      out.write("						                      + \"<td class='price' style='padding-top:8%;'>\"+list[i].price +\"원</td>\"\r\n");
      out.write("						                      + \"<td style='padding-top:5%;'> \"\r\n");
      out.write("						                      + \"<a href='");
      out.print( contextPath );
      out.write("/addBasket.ba?count=1&bno=\" + list[i].bookNo + \"' class='btn btn-outline-dark' style='padding-top:0px; padding-bottom:0px; width: 130px;'>장바구니 담기</a>\"\r\n");
      out.write("						                      + \"<br>\"\r\n");
      out.write("			                                  + \"<a href='");
      out.print( contextPath );
      out.write("/buyNow.or?count=1&bno=\" + list[i].bookNo + \"' class='btn btn-outline-dark' style='padding-top:0px; padding-bottom:0px; width: 130px;'>바로구매</a>\"\r\n");
      out.write("			                                  + \"<br>\"\r\n");
      out.write("			                                  + \"<a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=\"+list[i].bookNo +\"&review=Y' class='btn btn-outline-dark' style='padding-top:0px; padding-bottom:0px; width: 130px;'>리뷰 보기</a></td>\"\r\n");
      out.write("						                + \"</tr>\";\r\n");
      out.write("							}\r\n");
      out.write("						} else {\r\n");
      out.write("							result = \"<tr><td>검색된 리스트가 없습니다.</td></tr>\";\r\n");
      out.write("							\r\n");
      out.write("						}\r\n");
      out.write("						$(\"#searchTbody\").html(result);\r\n");
      out.write("					},\r\n");
      out.write("					\r\n");
      out.write("					error : function() {\r\n");
      out.write("						console.log(\"검색결과용 ajax 실패\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("        </script>\r\n");
      out.write("            <!-- 알터 출력용 -->\r\n");
      out.write("		<script>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\"; \r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") { \r\n");
      out.write("			alert(msg);\r\n");
      out.write("	\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("     \r\n");
      out.write("  </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<section class=\"py-5\" style=\"border-top: 1px solid rgb(199, 196, 196);\" id=\"mainSection\">\r\n");
      out.write("            <div class=\"container px-4 px-lg-5 mt-1\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span class=\"fw-bolder display-6\">베스트 도서</span>\r\n");
      out.write("                    <button class=\"btn btn-outline-dark mt-auto\" style=\"float: right;\" onclick=\"bookSearch('best','','title');\">더보기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\" style=\"clear: right;\">\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 for(int i = 0; i < bmlist.size(); i++) { 
      out.write("\r\n");
      out.write("                        <div class=\"col mb-5\">\r\n");
      out.write("                            <div class=\"card h-100\">\r\n");
      out.write("                                <!-- Product image-->\r\n");
      out.write("                                <a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=");
      out.print( bmlist.get(i).getBookNo() );
      out.write("' style=\"height: 65%;\"><img class=\"card-img-top\"  style=\"height: 100%;\" src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( bmlist.get(i).getFilePath() + bmlist.get(i).getChangeName() );
      out.write("\" /></a>\r\n");
      out.write("                                <!-- Product details-->\r\n");
      out.write("                                <div class=\"card-body p-4\" style=\"border-top: 1px solid rgb(199, 196, 196);\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <!-- Product name-->\r\n");
      out.write("                                        <h5 class=\"fw-bolder\">");
      out.print( bmlist.get(i).getTitle() );
      out.write("</h5>\r\n");
      out.write("                                        <!-- Product price-->\r\n");
      out.write("                                        <div style=\"color: red;\">30% 할인 ↓</div>\r\n");
      out.write("                                        <span>할인가 ");
      out.print( bmlist.get(i).getPrice() );
      out.write(" 원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Product actions-->\r\n");
      out.write("                                <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=");
      out.print( bmlist.get(i).getBookNo() );
      out.write("' class=\"btn btn-outline-dark mt-auto\">자세히보기</a>\r\n");
      out.write("                                        <a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=");
      out.print( bmlist.get(i).getBookNo() );
      out.write("&review=Y' class=\"btn btn-outline-dark mt-auto\">리뷰보기</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"container px-4 px-lg-5 mt-1\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span class=\"fw-bolder display-6\">신간 도서</span>\r\n");
      out.write("                    <button class=\"btn btn-outline-dark mt-auto\" style=\"float: right;\" onclick=\"bookSearch('new','','title');\">더보기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\r\n");
      out.write("                    ");
 for(int i = 0; i < bmNewlist.size(); i++) { 
      out.write("\r\n");
      out.write("                        <div class=\"col mb-5\">\r\n");
      out.write("                            <div class=\"card h-100\">\r\n");
      out.write("                                <!-- Product image-->\r\n");
      out.write("                                <a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=");
      out.print( bmNewlist.get(i).getBookNo() );
      out.write("' style=\"height: 65%;\"><img class=\"card-img-top\" style=\"height: 100%;\" src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( bmNewlist.get(i).getFilePath() + bmNewlist.get(i).getChangeName() );
      out.write("\" /></a>\r\n");
      out.write("                                <!-- Product details-->\r\n");
      out.write("                                <div class=\"card-body p-4\" style=\"border-top: 1px solid rgb(199, 196, 196);\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <!-- Product name-->\r\n");
      out.write("                                        <h5 class=\"fw-bolder\">");
      out.print( bmNewlist.get(i).getTitle() );
      out.write("</h5>\r\n");
      out.write("                                        <!-- Product price-->\r\n");
      out.write("                                        <div style=\"color: red;\">30% 할인 ↓</div>\r\n");
      out.write("                                        <span>할인가 ");
      out.print( bmNewlist.get(i).getPrice() );
      out.write(" 원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Product actions-->\r\n");
      out.write("                                <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=");
      out.print( bmNewlist.get(i).getBookNo() );
      out.write("' class=\"btn btn-outline-dark mt-auto\">자세히보기</a>\r\n");
      out.write("                                        <a href='");
      out.print( contextPath );
      out.write("/productUserDetail.mi?bno=");
      out.print( bmNewlist.get(i).getBookNo() );
      out.write("&review=Y' class=\"btn btn-outline-dark mt-auto\">리뷰보기</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <section class=\"py-5\" style=\"border-top: 1px solid rgb(199, 196, 196);display: none;\" id=\"searchResult\" >\r\n");
      out.write("	            <header class=\"py-5\">\r\n");
      out.write("		            <div class=\"container px-lg-5\">\r\n");
      out.write("		                <div class=\"text-center\">\r\n");
      out.write("		                    <h3 id=\"searchType\">낮은가격 검색결과</h3>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                \r\n");
      out.write("		                <div>\r\n");
      out.write("		                    <button class=\"btn btn-mini\" onclick=\"bookSearch('','','title');\">제목순</button>|<button class=\"btn btn-mini\" onclick=\"bookSearch('','','dPub');\">출간일</button>|<button class=\"btn btn-mini\" onclick=\"bookSearch('','','lowPrice');\">낮은가격</button> |<button class=\"btn btn-mini\" onclick=\"bookSearch('','','highPrice');\">높은가격</button> \r\n");
      out.write("		                </div>\r\n");
      out.write("		                <div class=\"p-4 p-lg-5 bg-light rounded-3 text-center\">\r\n");
      out.write("		                    <table id=\"searchTable\" class=\"table text-center\" >\r\n");
      out.write("		                        <tbody id=\"searchTbody\">\r\n");
      out.write("		                        </tbody>\r\n");
      out.write("		                    </table>\r\n");
      out.write("		                </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </header>\r\n");
      out.write("       		</section>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	    <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2021</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
if(category != null) {
      out.write("\r\n");
      out.write("bookSearch('category',");
      out.print(category);
      out.write(",'title');\r\n");
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
