/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-12 04:28:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.main.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.admin.product.model.vo.Attachment;
import com.kh.admin.product.model.vo.BookMaster;
import com.kh.member.model.vo.Member;

public final class productUserDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/main/search/../../common/main_end.jsp", Long.valueOf(1638543132000L));
    _jspx_dependants.put("/views/main/search/../../common/main_top.jsp", Long.valueOf(1639217625350L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.admin.product.model.vo.BookMaster");
    _jspx_imports_classes.add("com.kh.admin.product.model.vo.Attachment");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	BookMaster p = (BookMaster)request.getAttribute("p");

	Attachment at = (Attachment)request.getAttribute("at");

	int bookNo = (int)request.getAttribute("bookNo");
	
	String review = (String)request.getAttribute("review");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
	
	String contextPath = request.getContextPath(); 
	Member loginUser = (Member)session.getAttribute("loginUser");
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"");
      out.print(contextPath);
      out.write("\">북적북적</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print(contextPath);
      out.write("\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print(contextPath);
      out.write("/PwdForm.me\">MyPage</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print( contextPath );
      out.write("/faqForm.fa\">고객센터</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print( contextPath );
      out.write("/noticeList.ad\">공지사항</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Category</a>\r\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=1\">소설</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=2\">에세이</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=3\">역사</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=4\">과학</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=5\">정치</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=6\">로맨틱</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form class=\"d-flex\">\r\n");
      out.write("				<a href=\"");
      out.print( contextPath );
      out.write("/list.ba\" class=\"btn btn-outline-light\"\r\n");
      out.write("					type=\"submit\"> <i class=\"bi-cart-fill me-1\"></i> Cart <span\r\n");
      out.write("					class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\r\n");
      out.write("				</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<!-- 로그인 전 -->\r\n");
      out.write("\r\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"button\"\r\n");
      out.write("					onclick=\"location.href = '");
      out.print( contextPath );
      out.write("/loginForm.me'\">\r\n");
      out.write("\r\n");
      out.write("					Login</button>\r\n");
      out.write("				<!-- 로그인 후 -->\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"button\"\r\n");
      out.write("					onclick=\"location.href = '");
      out.print( contextPath );
      out.write("/logout.me'\">\r\n");
      out.write("\r\n");
      out.write("					Logout</button>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<button style=\"color: withe;\" class=\"btn btn-outline-light\"\r\n");
      out.write("					type=\"button\">\r\n");
      out.write("					");
      out.print(loginUser.getUserName() );
      out.write("회원님 환영합니다.\r\n");
      out.write("				</button>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/main.mi\"><img\r\n");
      out.write("						src=\"/semi/resources/logo.png\" title=\"로고\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 알터 출력용 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\"; \r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") { \r\n");
      out.write("			alert(msg);\r\n");
      out.write("	\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"container mt-5\">\r\n");
      out.write("            <div align=\"center\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <!-- content-->\r\n");
      out.write("                    <article>\r\n");
      out.write("                        <!-- page header-->\r\n");
      out.write("                        <header>\r\n");
      out.write("                            <!-- Post title-->\r\n");
      out.write("                            <h1 class=\"fw-bolder mb-1\">");
      out.print( p.getBookTitle() );
      out.write("</h1>\r\n");
      out.write("                            <!-- Post meta content-->\r\n");
      out.write("                            <div class=\"text-muted \">");
      out.print( p.getAuthor() );
      out.write(" |  ");
      out.print( p.getPublisher() );
      out.write("  | ");
      out.print( p.getPblctDate() );
      out.write(" </div>\r\n");
      out.write("                            <!-- Post categories-->\r\n");
      out.write("                            <span class=\"badge bg-secondary text-decoration-none link-light\">#");
      out.print( p.getTag1() );
      out.write("</span>\r\n");
      out.write("                            <span class=\"badge bg-secondary text-decoration-none link-light\">#");
      out.print( p.getTag2() );
      out.write("</span>\r\n");
      out.write("                        </header>\r\n");
      out.write("                        <!-- Page content-->\r\n");
      out.write("                        <section>\r\n");
      out.write("                            <div class=\"px-4 px-lg-5 my-5\">\r\n");
      out.write("                                <div class=\"row gx-4 gx-lg-5 align-items-center\">\r\n");
      out.write("                                    <div class=\"col-md-6\"><img class=\"card-img-top\" style=\"width: 80%;\" src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( at.getFilePath() + at.getChangeName() );
      out.write("\"></div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <h2 class=\"fw-bolder\">");
      out.print( p.getTitle() );
      out.write("</h2>\r\n");
      out.write("                                        <div class=\"fs-5 mb-1\" style=\"color: red;\">30% 할인 ↓</div>\r\n");
      out.write("                                        <h3 class=\"fw-bolder mb-5\">판매가 : ");
      out.print( p.getPrice() );
      out.write(" 원</h3>\r\n");
      out.write("                                        <div class=\"d-flex\" align=\"center\" style=\"margin-left: 70px;\">\r\n");
      out.write("                                        	\r\n");
      out.write("                                        	<form action=\"");
      out.print( contextPath );
      out.write("/addBasket.ba?bno=");
      out.print( bookNo );
      out.write("\" method=\"post\">\r\n");
      out.write("                                        		<table>\r\n");
      out.write("                                        			<tr>\r\n");
      out.write("                                        				<td>\r\n");
      out.write("                                        					 <input class=\"form-control text-center me-3\" id=\"inputQuantity\" type=\"number\" value=\"1\" style=\"max-width: 4rem\" name=\"count\" min=\"1\">\r\n");
      out.write("                                        				</td>\r\n");
      out.write("                                        				<td>\r\n");
      out.write("                                        					<button class=\"btn btn-outline-dark flex-shrink-0\" type=\"submit\">\r\n");
      out.write("				                                                <i class=\"bi-cart-fill me-1\"></i>\r\n");
      out.write("				                                                Add to cart\r\n");
      out.write("				                                            </button>\r\n");
      out.write("                                        				</td>\r\n");
      out.write("                                        			</tr>\r\n");
      out.write("                                        		</table>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <!-- Post content-->\r\n");
      out.write("                        <section class=\"mb-5\" align=\"left\">\r\n");
      out.write("                            <h2 class=\"fw-bolder mb-4\">");
      out.print( p.getBookHead() );
      out.write("</h2>\r\n");
      out.write("                            <p class=\"fs-5 mb-3\">");
      out.print( p.getBookContent() );
      out.write("</p>\r\n");
      out.write("                            <h2 class=\"fw-bolder mb-4 mt-5\">저자소개</h2>\r\n");
      out.write("                            <p class=\"fs-5 mb-4\">");
      out.print( p.getAuthorInfo() );
      out.write("</p>\r\n");
      out.write("                        \r\n");
      out.write("                        </section>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <!-- Comments section-->\r\n");
      out.write("                    <section class=\"mb-5\">\r\n");
      out.write("                        <div class=\"card bg-light\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <!-- Comment form-->\r\n");
      out.write("                                <div>\r\n");
      out.write("                                <p style=\"color:red;\">로그인 시에만 작성이 가능합니다.</p>\r\n");
      out.write("                                <table width = \"100%\" height = \"100%\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                	<td align=\"center\" width = \"80%\" height=\"100%\"><textarea id=\"scrollbottom\" style=\"width: 100%; resize: none; display:inline-block\" class=\"form-control\" rows=\"3\" placeholder=\"이 책에 대한 당신의 감상을 남기세요!\"></textarea></td>\r\n");
      out.write("                                	<td align=\"center\"   width = \"20%\"  height = \"100%\"><button class=\"btn btn-dark\" style=\"display:inline=block; width:100%; height:100%\" type=\"button\" onclick=\"insertComment();\">등록</button></td>\r\n");
      out.write("                                </tr>	\r\n");
      out.write("                                </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Comment with nested comments-->\r\n");
      out.write("                                <div id = \"commentList\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	    <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2021</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
if(review != null) {
      out.write("\r\n");
      out.write("//포커스 이동\r\n");
      out.write("$('#scrollbottom').focus();\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("function commentList(){\r\n");
      out.write("	var obj = {};\r\n");
      out.write("	obj.bookNo = ");
      out.print(bookNo);
      out.write(";\r\n");
      out.write("	$.ajax ({\r\n");
      out.write("		url : \"clist.co\",\r\n");
      out.write("		data : obj,\r\n");
      out.write("		success : function(list) {\r\n");
      out.write("			var result = \"\";\r\n");
      out.write("        \r\n");
      out.write("			for(var i in list) { // for in\r\n");
      out.write("				result += '<div class=\"d-flex\">'\r\n");
      out.write("		                      + '<div class=\"flex-shrink-0\"><img class=\"rounded-circle\" src=\"https://dummyimage.com/50x50/ced4da/6c757d.jpg\" alt=\"...\" /></div>'\r\n");
      out.write("		                      + '<div class=\"ms-3\">'\r\n");
      out.write("		                      + '<div class=\"fw-bold\" align=\"left\">' +list[i].userNo +'</div>'\r\n");
      out.write("		                      + list[i].cment \r\n");
      out.write("                              + '</div>'\r\n");
      out.write("                              + '</div>';\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#commentList\").html(result);\r\n");
      out.write("		},\r\n");
      out.write("		\r\n");
      out.write("		error : function() {\r\n");
      out.write("			console.log(\"검색결과용 ajax 실패\");\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function insertComment(){\r\n");
      out.write("\r\n");
      out.write("	var obj = {};\r\n");
      out.write("	obj.bookNo = ");
      out.print(bookNo);
      out.write(";\r\n");
      out.write("	obj.cment = $('#scrollbottom').val();\r\n");
      out.write("	$.ajax ({\r\n");
      out.write("		url : \"insertcomment.co\",\r\n");
      out.write("		data : obj,\r\n");
      out.write("		success : function(list) {\r\n");
      out.write("			$('#scrollbottom').val(\"\");\r\n");
      out.write("			commentList();	\r\n");
      out.write("		},\r\n");
      out.write("		error : function() {\r\n");
      out.write("			console.log(\"검색결과용 ajax 실패\");\r\n");
      out.write("		}\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("commentList();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
