/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-12 04:43:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class faqForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/faq/../common/main_end.jsp", Long.valueOf(1638543132000L));
    _jspx_dependants.put("/views/faq/../common/main_top.jsp", Long.valueOf(1639217625350L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FAQ</title>\r\n");
      out.write("<link href=\"css/forFAQ.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
	
	String contextPath = request.getContextPath(); 
	Member loginUser = (Member)session.getAttribute("loginUser");
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"");
      out.print(contextPath);
      out.write("\">북적북적</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print(contextPath);
      out.write("\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print(contextPath);
      out.write("/PwdForm.me\">MyPage</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print( contextPath );
      out.write("/faqForm.fa\">고객센터</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print( contextPath );
      out.write("/noticeList.ad\">공지사항</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Category</a>\r\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=1\">소설</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=2\">에세이</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=3\">역사</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=4\">과학</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=5\">정치</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=6\">로맨틱</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form class=\"d-flex\">\r\n");
      out.write("				<a href=\"");
      out.print( contextPath );
      out.write("/list.ba\" class=\"btn btn-outline-light\"\r\n");
      out.write("					type=\"submit\"> <i class=\"bi-cart-fill me-1\"></i> Cart <span\r\n");
      out.write("					class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\r\n");
      out.write("				</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<!-- 로그인 전 -->\r\n");
      out.write("\r\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"button\"\r\n");
      out.write("					onclick=\"location.href = '");
      out.print( contextPath );
      out.write("/loginForm.me'\">\r\n");
      out.write("\r\n");
      out.write("					Login</button>\r\n");
      out.write("				<!-- 로그인 후 -->\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"button\"\r\n");
      out.write("					onclick=\"location.href = '");
      out.print( contextPath );
      out.write("/logout.me'\">\r\n");
      out.write("\r\n");
      out.write("					Logout</button>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<button style=\"color: withe;\" class=\"btn btn-outline-light\"\r\n");
      out.write("					type=\"button\">\r\n");
      out.write("					");
      out.print(loginUser.getUserName() );
      out.write("회원님 환영합니다.\r\n");
      out.write("				</button>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/main.mi\"><img\r\n");
      out.write("						src=\"/semi/resources/logo.png\" title=\"로고\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 알터 출력용 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\"; \r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") { \r\n");
      out.write("			alert(msg);\r\n");
      out.write("	\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("         <div class=\"row justify-content-center\">\r\n");
      out.write("             <div class=\"col-lg-11\">\r\n");
      out.write("                 <div class=\"card border-1 rounded-lg mt-5\">\r\n");
      out.write("                     <div class=\"card-header\"><h4 class=\"text-center font-weight-light my-1\">FAQ</h4></div>\r\n");
      out.write("                     <div class=\"card-body\">\r\n");
      out.write("                             <div class=\"form-floating mb-3\">\r\n");
      out.write("                                 <div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     \r\n");
      out.write("                                     <strong>자주 묻는 질문들 입니다 </strong><br> 더 궁금한 사항이 있으시면 1대1 문의를 이용해 주세요.<br>\r\n");
      out.write("         							 <a id=\"oneToOne\" href=\"");
      out.print(contextPath );
      out.write("//inquiryForm.in?currentPage=1\">1대1문의 바로가기</a>\r\n");
      out.write("	           						\r\n");
      out.write("                                     \r\n");
      out.write("                                 </div>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc()\" ><h4>회원가입은 어디서 하나요?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong>회원가입 방법입니다. </strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> PC 홈페이지 접속 → 우측상단 로그인 버튼 클릭 → 회원가입 버튼클릭 하시면 회원가입이 가능합니다. <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                              <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc1()\" ><h4>탈퇴는 어떻게 하나요 ?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content1\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong>회원탈퇴 이용 방법 </strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> PC 홈페이지 접속 → [마이페이지] 접속 후  My정보 → 회원탈퇴에서 회원 탈퇴가 가능합니다. <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                               <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc2()\" ><h4>주문한 상품은 언제 받을 수 있을까요 ?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content2\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong>배송 예정일 </strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> \r\n");
      out.write("											도서산간지역은 근무일 기준 3일 이내입니다.\r\n");
      out.write("											\r\n");
      out.write("											연휴/공휴일이 있을 경우 해당기간 제외 후 배송 기간을 산정합니다.\r\n");
      out.write("											\r\n");
      out.write("											택배사 사정이나 기상악화의 경우는 배송일이 다소 변경될 수 있습니다.\r\n");
      out.write("											\r\n");
      out.write("											3. 해피머니 문화상품권은 어떻게 사용하나요 ?\r\n");
      out.write("											북적북적에서는 아직 해피머니 문화상품권을 사용하실 수 없습니다.\r\n");
      out.write("                                     \r\n");
      out.write("                                     <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             \r\n");
      out.write("                                 <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc3()\" ><h4>배송비는 얼마인가요?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content3\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong>배송비 관련 규정 </strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> \r\n");
      out.write("											북적북적에서는 한 개 이상 구매시 모두 무료 배송입니다\r\n");
      out.write("                                     \r\n");
      out.write("                                     <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             \r\n");
      out.write("                                 <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc4()\" ><h4>북적북적에서 사용 가능한 결제수단은 어떤 것들이 있나요 ?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content4\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong>결제 수단 </strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> \r\n");
      out.write("											당사에서는 회원님들께 \"신용카드 결제\" 수단을 제공하고 있습니다\r\n");
      out.write("                                     \r\n");
      out.write("                                     <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             \r\n");
      out.write("                                   <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc5()\" ><h4>신용카드 결제 후, 부분 취소는 어떻게 하나요 ?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content5\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong>환불규정</strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> \r\n");
      out.write("											홈페이지 통해 직접 부분취소 하는 경우에는 신용카드 재승인으로 처리 되며,\r\n");
      out.write("											고객센터를 통한 부분취소 시에는 신용카드 부분 취소가 됩니다.(일부카드는 예치금으로 환불)\r\n");
      out.write("                                     \r\n");
      out.write("                                     <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             \r\n");
      out.write("                                    <!-- 질문 div -->\r\n");
      out.write("                             <div>\r\n");
      out.write("                             	<span id=\"toc-toggle\" onclick=\"openCloseToc6()\" ><h4>주문 취소는 어디서 하나요 ?</h4></span>\r\n");
      out.write("                                 <ol id=\"toc-content6\" style=\"display : none\">\r\n");
      out.write("								  	<div class=\"alert alert-warning alert-dismissible\" role=\"alert\">\r\n");
      out.write("                                     <!-- 답변 제목 -->\r\n");
      out.write("                                     <strong> 주문 취소방법</strong>\r\n");
      out.write("                                     <!-- 내용-->\r\n");
      out.write("                                     <br> \r\n");
      out.write("											\r\n");
      out.write("\r\n");
      out.write("											취소 방법은 아래와 같습니다.\r\n");
      out.write("											\r\n");
      out.write("											\r\n");
      out.write("											1) 마이페이지 > My 쇼핑 > 주문/배송 조회\r\n");
      out.write("											\r\n");
      out.write("											2) 주문내역/배송조회 페이지의 주문한 내역을 확인하고 주문번호를 클릭\r\n");
      out.write("											\r\n");
      out.write("											3) 취소하려는 상품 우측의 버튼 선택을 체크하고 [주문취소]를 클릭\r\n");
      out.write("\r\n");
      out.write("                                     \r\n");
      out.write("                                     <br>\r\n");
      out.write("                            \r\n");
      out.write("                                 </div>\r\n");
      out.write("								 </ol>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             \r\n");
      out.write("                             \r\n");
      out.write("                    \r\n");
      out.write("                     </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc() {\r\n");
      out.write("    if(document.getElementById('toc-content').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc1() {\r\n");
      out.write("    if(document.getElementById('toc-content1').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content1').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content1').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc2() {\r\n");
      out.write("    if(document.getElementById('toc-content2').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content2').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content2').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc3() {\r\n");
      out.write("    if(document.getElementById('toc-content3').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content3').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content3').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc4() {\r\n");
      out.write("    if(document.getElementById('toc-content4').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content4').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content4').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc6() {\r\n");
      out.write("    if(document.getElementById('toc-content6').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content6').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content6').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  function openCloseToc5() {\r\n");
      out.write("    if(document.getElementById('toc-content5').style.display === 'block') {\r\n");
      out.write("      document.getElementById('toc-content5').style.display = 'none';\r\n");
      out.write(" \r\n");
      out.write("    } else {\r\n");
      out.write("      document.getElementById('toc-content5').style.display = 'block';\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	    <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2021</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
