/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-12 01:51:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.basket.model.vo.Basket;
import com.kh.member.model.vo.Member;

public final class paymentView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/order/../common/main_top.jsp", Long.valueOf(1639217625350L));
    _jspx_dependants.put("/views/order/../common/main_end.jsp", Long.valueOf(1638543132000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.basket.model.vo.Basket");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Basket> atList = (ArrayList<Basket>)request.getAttribute("atList");

      out.write("\r\n");
      out.write("<!-- 위 고길동 에 이거 사용하면 값 가져와짐 : (String)session.getAttribute(\"userName\") [주소 또한 이와같이 해볼것]-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script> <!-- 온라인 방식 -->\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 다음 주소 검색 API -->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.bookList>td {\r\n");
      out.write("        text-align : center;\r\n");
      out.write("        vertical-align : middle;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
	
	String contextPath = request.getContextPath(); 
	Member loginUser = (Member)session.getAttribute("loginUser");
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"");
      out.print(contextPath);
      out.write("\">북적북적</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print(contextPath);
      out.write("\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print(contextPath);
      out.write("/PwdForm.me\">MyPage</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print( contextPath );
      out.write("/faqForm.fa\">고객센터</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"");
      out.print( contextPath );
      out.write("/noticeList.ad\">공지사항</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Category</a>\r\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=1\">소설</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=2\">에세이</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=3\">역사</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=4\">과학</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=5\">정치</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.print( contextPath );
      out.write("/main.mi?category=6\">로맨틱</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form class=\"d-flex\">\r\n");
      out.write("				<a href=\"");
      out.print( contextPath );
      out.write("/list.ba\" class=\"btn btn-outline-light\"\r\n");
      out.write("					type=\"submit\"> <i class=\"bi-cart-fill me-1\"></i> Cart <span\r\n");
      out.write("					class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\r\n");
      out.write("				</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<!-- 로그인 전 -->\r\n");
      out.write("\r\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"button\"\r\n");
      out.write("					onclick=\"location.href = '");
      out.print( contextPath );
      out.write("/loginForm.me'\">\r\n");
      out.write("\r\n");
      out.write("					Login</button>\r\n");
      out.write("				<!-- 로그인 후 -->\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"button\"\r\n");
      out.write("					onclick=\"location.href = '");
      out.print( contextPath );
      out.write("/logout.me'\">\r\n");
      out.write("\r\n");
      out.write("					Logout</button>\r\n");
      out.write("				&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<button style=\"color: withe;\" class=\"btn btn-outline-light\"\r\n");
      out.write("					type=\"button\">\r\n");
      out.write("					");
      out.print(loginUser.getUserName() );
      out.write("회원님 환영합니다.\r\n");
      out.write("				</button>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/main.mi\"><img\r\n");
      out.write("						src=\"/semi/resources/logo.png\" title=\"로고\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 알터 출력용 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\"; \r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") { \r\n");
      out.write("			alert(msg);\r\n");
      out.write("	\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		 <!-- Responsive navbar-->\r\n");
      out.write("		 <!-- \r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("            <div class=\"container px-lg-5\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#!\">Start Bootstrap</a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"index.html\">메인 페이지</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\">마이 페이지</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("         -->\r\n");
      out.write("        <!-- Header-->\r\n");
      out.write("        <header class=\"py-5\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/order.ba\" methd=\"post\">\r\n");
      out.write("            <!-- 주문 상품 정보 -->\r\n");
      out.write("            <div class=\"container px-lg-5\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h1>결 제</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"p-4 p-lg-5 bg-light rounded-3\">\r\n");
      out.write("                    <b>● 주문 상품 정보</b>\r\n");
      out.write("                    <table id=\"table\" class=\"table text-center\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th style=\"width:16%;\">책 이미지</th>\r\n");
      out.write("                            <th>책 제목</th>\r\n");
      out.write("                            <th>가격</th>\r\n");
      out.write("                            <th>수량</th>\r\n");
      out.write("                            <th>소계</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 for(Basket b : atList) { 
      out.write("\r\n");
      out.write("                        	<input type=\"hidden\" value=\"");
      out.print( b.getBasketSeq() );
      out.write("\" name=\"basketNo\">\r\n");
      out.write("	                        <tr class=\"bookList\">\r\n");
      out.write("	                            <td><img src=\"");
      out.print( request.getContextPath() );
      out.write('/');
      out.print( b.getTitleImg() );
      out.write("\" style=\"width:80%;\"></td>\r\n");
      out.write("	                            <td class=\"title\" name=\"title\">");
      out.print( b.getBookTitle() );
      out.write("</td>\r\n");
      out.write("	                            <td class=\"price\" name=\"price\">");
      out.print( b.getPrice() );
      out.write("</td>\r\n");
      out.write("	                            <td class=\"count\" name=\"count\">");
      out.print( b.getCount() );
      out.write("</td>\r\n");
      out.write("	                            <td class=\"priceSum\" name=\"priceSum\">");
      out.print( b.getSumPrice() );
      out.write("</td>\r\n");
      out.write("	                        </tr>\r\n");
      out.write("                       	");
 } 
      out.write("\r\n");
      out.write("                        <!-- \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"http://image.yes24.com/momo/TopCate725/MidCate004/72435140.jpg\" style=\"width:80%;\"></td>\r\n");
      out.write("                            <td class=\"title\" style=\"padding-top:8%;\" name=\"title\">장발장</td>\r\n");
      out.write("                            <td class=\"price\" style=\"padding-top:8%;\" name=\"price\">6000</td>\r\n");
      out.write("                            <td class=\"count\" style=\"padding-top:8%;\" name=\"count\">2</td>\r\n");
      out.write("                            <td class=\"priceSum\" style=\"padding-top:8%;\" name=\"priceSum\">12000</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("						 -->\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td>총계</td>\r\n");
      out.write("                        <td id=\"allCount\" name=\"allCount\"></td>\r\n");
      out.write("                        <td id=\"allSum\" name=\"allSum\">\r\n");
      out.write("                            \r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                        \r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                    <script>\r\n");
      out.write("                        // 총계\r\n");
      out.write("                        var table = document.getElementById('table');\r\n");
      out.write("                            var sum = 0;\r\n");
      out.write("                        for(var i =1; i < table.rows.length - 1; i++) {\r\n");
      out.write("                            sum += parseInt(table.rows[i].cells[3].innerHTML);\r\n");
      out.write("                            console.log(\"sum : \" + sum);\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        document.getElementById('allCount').innerHTML = parseInt(sum);\r\n");
      out.write("                    </script>\r\n");
      out.write("\r\n");
      out.write("                    <table style=\"width:100%;\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/list.ba\" class=\"btn btn-secondary\" style=\"text-align:left;\">장바구니 돌아가기</a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 배송방법 선택 -->\r\n");
      out.write("            <!--\r\n");
      out.write("            <div class=\"container px-lg-5\">\r\n");
      out.write("                <div class=\"p-4 p-lg-5 bg-light rounded-3\">\r\n");
      out.write("                    <b>● 배송 방법 선택</b>\r\n");
      out.write("                    <table id=\"table\" class=\"table\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td style=\"width:20%\"><b>배송방법</b></td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                    <input type=\"radio\" id=\"post\">택배 <br>\r\n");
      out.write("                                    <input type=\"radio\" id=\"self\">직접 수령 <br>   \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 배송지 정보 입력 -->\r\n");
      out.write("            <div class=\"container px-lg-5\">\r\n");
      out.write("                <div class=\"p-4 p-lg-5 bg-light rounded-3\">\r\n");
      out.write("                    <!-- 택배 -->\r\n");
      out.write("                    <b>● 배송지 정보 입력</b>\r\n");
      out.write("                    <p style=\"color:red; display:inline;  font-size:12px;\">( * 필수 입력 항목 )</p>\r\n");
      out.write("                    \r\n");
      out.write("                    <table id=\"table\" class=\"table\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p style=\"color:red; display:inline\">*</p>\r\n");
      out.write("                                   	주문인\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input id=\"order\" type=\"text\" name=\"order\" required>\r\n");
      out.write("                                    <input type=\"button\" onclick=\"getName();\" value=\"현재 이름 가져오기\">\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p style=\"color:red; display:inline\">*</p>\r\n");
      out.write("                                    	받으시는 분\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input id=\"receipt\" type=\"text\" name=\"receipt\" required>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p style=\"color:red; display:inline\">*</p>\r\n");
      out.write("                                   	 주 소\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <!-- 다음 주소 API 검색 방법 사용 시작 -->\r\n");
      out.write("                                    <input type=\"text\" id=\"postcode\" placeholder=\"우편번호\" name=\"postNo\" required readonly>\r\n");
      out.write("									<input type=\"button\" onclick=\"execDaumPostcode()\" value=\"주소 찾기\">\r\n");
      out.write("									<input type=\"button\" onclick=\"getAllPost()\" value=\"기록한 주소 가져오기\"><br>\r\n");
      out.write("									<input type=\"text\" id=\"roadAddress\" placeholder=\"도로명주소\" name=\"address\" required readonly>\r\n");
      out.write("									<br>\r\n");
      out.write("									<span id=\"guide\" style=\"color:#999;display:none\"></span>\r\n");
      out.write("									<input type=\"text\" id=\"detailAddress\" placeholder=\"상세주소\" required name=\"detailAddress\" required>\r\n");
      out.write("									\r\n");
      out.write("									<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("									<script>\r\n");
      out.write("										// 회원정보에 입력된 내용 가져오기\r\n");
      out.write("										function getAllPost() {\r\n");
      out.write("											$(this).click(function() {\r\n");
      out.write("												$(\"#postcode\").attr(\"value\", \"");
      out.print(loginUser.getPostNo() );
      out.write("\")\r\n");
      out.write("												$(\"#roadAddress\").attr(\"value\", \"");
      out.print( loginUser.getAddress() );
      out.write("\")\r\n");
      out.write("												$(\"#detailAddress\").attr(\"value\", \"");
      out.print( loginUser.getDetailAddress() );
      out.write("\")\r\n");
      out.write("											})\r\n");
      out.write("										}\r\n");
      out.write("									\r\n");
      out.write("									    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("									    function execDaumPostcode() {\r\n");
      out.write("									        new daum.Postcode({\r\n");
      out.write("									            oncomplete: function(data) {\r\n");
      out.write("									                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("									\r\n");
      out.write("									                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("									                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("									                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("									                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("									\r\n");
      out.write("									                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("									                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("									                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("									                    extraRoadAddr += data.bname;\r\n");
      out.write("									                }\r\n");
      out.write("									                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("									                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("									                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("									                }\r\n");
      out.write("									                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("									                if(extraRoadAddr !== ''){\r\n");
      out.write("									                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("									                }\r\n");
      out.write("									\r\n");
      out.write("									                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("									                document.getElementById('postcode').value = data.zonecode;\r\n");
      out.write("									                document.getElementById(\"roadAddress\").value = roadAddr;\r\n");
      out.write("									                document.getElementById(\"jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("									                \r\n");
      out.write("									                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("									                if(roadAddr !== ''){\r\n");
      out.write("									                    document.getElementById(\"extraAddress\").value = extraRoadAddr;\r\n");
      out.write("									                } else {\r\n");
      out.write("									                    document.getElementById(\"extraAddress\").value = '';\r\n");
      out.write("									                }\r\n");
      out.write("									\r\n");
      out.write("									                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("									                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("									                if(data.autoRoadAddress) {\r\n");
      out.write("									                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("									                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("									                    guideTextBox.style.display = 'block';\r\n");
      out.write("									\r\n");
      out.write("									                } else if(data.autoJibunAddress) {\r\n");
      out.write("									                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("									                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("									                    guideTextBox.style.display = 'block';\r\n");
      out.write("									                } else {\r\n");
      out.write("									                    guideTextBox.innerHTML = '';\r\n");
      out.write("									                    guideTextBox.style.display = 'none';\r\n");
      out.write("									                }\r\n");
      out.write("									            }\r\n");
      out.write("									        }).open();\r\n");
      out.write("									    }\r\n");
      out.write("									</script>\r\n");
      out.write("                                    <!-- 다음 주소 API 검색 방법 끝 -->\r\n");
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p style=\"color:red; display:inline; \">*</p>\r\n");
      out.write("                                   	휴대전화번호\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"text\" id=\"phone\" name=\"phone\" maxlength=\"13\" placeholder=\"-포함여 13자리 입력하세요\" required>\r\n");
      out.write("                                    <input type=\"button\" onclick=\"getPhone()\" value=\"전화번호 가져오기\">\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    \r\n");
      out.write("                    <script>\r\n");
      out.write("                    	function getName() {\r\n");
      out.write("                    		$(this).click(function() {\r\n");
      out.write("                    			$(\"#order\").attr(\"value\", \"");
      out.print( loginUser.getUserName() );
      out.write("\")\r\n");
      out.write("                    		})\r\n");
      out.write("                    	};\r\n");
      out.write("                    	\r\n");
      out.write("                    	function getPhone() {\r\n");
      out.write("	                		$(this).click(function() {\r\n");
      out.write("	                			$(\"#phone\").attr(\"value\",\"");
      out.print( loginUser.getPhone() );
      out.write("\")\r\n");
      out.write("	                		})\r\n");
      out.write("	                	};\r\n");
      out.write("                    </script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 결제 -->\r\n");
      out.write("            <div class=\"container px-lg-5\">\r\n");
      out.write("                <div class=\"p-4 p-lg-5 bg-light rounded-3\">\r\n");
      out.write("                    <b>● 카드 비밀번호 입력</b>\r\n");
      out.write("                    <p style=\"color:red; display:inline; font-size:12px;\">( 카드등록을 하지 않은 경우 결제를 진행할 수 없습니다.)</p>\r\n");
      out.write("                    <table id=\"table\" class=\"table\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>카드사</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <select id=\"cardName\" name=\"cardName\">\r\n");
      out.write("                                    <option value=\"신한\">신한카드</option>\r\n");
      out.write("                                    <option value=\"BC\">BC카드</option>\r\n");
      out.write("                                    <option value=\"케이뱅크\">케이뱅크카드 (BC)</option>\r\n");
      out.write("                                    <option value=\"카카오뱅크\">카카오뱅크 드(KB)</option>\r\n");
      out.write("                                    <option value=\"KB국민\">KB국민카드</option>\r\n");
      out.write("                                    <option value=\"KB아이행복\">KB아이행복(아이사랑)카드</option>\r\n");
      out.write("                                    <option value=\"KB고운맘\">KB고운맘카드</option>\r\n");
      out.write("                                    <option value=\"삼성\">삼성카드</option>\r\n");
      out.write("                                    <option value=\"현대\">현대카드</option>\r\n");
      out.write("                                    <option value=\"롯데\">롯데카드</option>\r\n");
      out.write("                                    <option value=\"하나\">하나카드</option>\r\n");
      out.write("                                    <option value=\"하나BC\">하나카드(BC카드)</option>\r\n");
      out.write("                                    <option value=\"NHBC\">NH채움카드(BC카드)</option>\r\n");
      out.write("                                    <option value=\"NH\"> NH채움카드</option>\r\n");
      out.write("                                    <option value=\"우리\">우리카드</option>\r\n");
      out.write("                                    <option value=\"우리BC\">우리카드(BC카드)</option>\r\n");
      out.write("                                    <option value=\"IBK\">IBK기업(BC카드)</option>\r\n");
      out.write("                                    <option value=\"UnionPay\">해외발급 Union Pay</option>\r\n");
      out.write("                                    <option value=\"VISA CARD\">해외발급 VISA CARD</option>\r\n");
      out.write("                                    <option value=\"MASTER CARD\">해외발급 MASTER CARD</option>\r\n");
      out.write("                                    <option value=\"JCB CARD\">해외발급 JCB CARD</option>\r\n");
      out.write("                                    <option value=\"씨티\">씨티카드</option>\r\n");
      out.write("                                    <option value=\"제주\">제주카드</option>\r\n");
      out.write("                                    <option value=\"광주\">광주카드</option>\r\n");
      out.write("                                    <option value=\"전북\">전북카드</option>\r\n");
      out.write("                                    <option value=\"산업은행\">산업은행카드</option>\r\n");
      out.write("                                    <option value=\"수협\">수협카드</option>\r\n");
      out.write("                                    <option value=\"우체국\">우체국카드</option>\r\n");
      out.write("                                    <option value=\"신협BC\">신협카드(BC카드)</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>카드번호</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" id=\"cardNum\" name=\"cardNum\" maxlength=\"19\" placeholder=\"- 포함하여 입력하세요\" required>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td style=\"width:20%;\">\r\n");
      out.write("                                	카드 비밀번호\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"password\" id=\"cardPwd\" name=\"cardPwd\" required>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div  class=\"text-center\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success\" onclick=\"return payment();\">결 제</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            // 총계\r\n");
      out.write("            var table = document.getElementById('table');\r\n");
      out.write("                var sum = 0;\r\n");
      out.write("            for(var i =1; i < table.rows.length - 1; i++) {\r\n");
      out.write("                sum += parseInt(table.rows[i].cells[4].innerHTML);\r\n");
      out.write("                console.log(\"sum : \" + sum);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            document.getElementById('allSum').innerHTML = parseInt(sum);\r\n");
      out.write("\r\n");
      out.write("            function payment() {\r\n");
      out.write("                // 주문인\r\n");
      out.write("                var regExp = /^[가-힣]{2,}$/;\r\n");
      out.write("                var order = document.getElementById('order').value;\r\n");
      out.write("                \r\n");
      out.write("                if(!regExp.test(order)){\r\n");
      out.write("                    alert(\"'주문인' 부분이 잘못되었습니다. 다시 입력해 주세요.\");\r\n");
      out.write("                    document.getElementById('order').focus();\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var receipt = document.getElementById('receipt').value;\r\n");
      out.write("                // 받으시는 분\r\n");
      out.write("                if(!regExp.test(receipt)){\r\n");
      out.write("                    alert(\"'받으시는 분' 부분이 잘못되었습니다. 다시 입력해 주세요.\");\r\n");
      out.write("                    document.getElementById('receipt').focus();\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                regExp = /^[0-9]{5}$/;\r\n");
      out.write("				\r\n");
      out.write("                \r\n");
      out.write("                // 주소\r\n");
      out.write("                /*\r\n");
      out.write("                // 우편번호\r\n");
      out.write("                var postcode = document.getElementById('postcode').value;\r\n");
      out.write("                if(!regExp.test(postcode)) {\r\n");
      out.write("                	alert(\"'우편번호' 부분이 잘못되었습니다. 다시 입력해 주세요.\");\r\n");
      out.write("                	document.getElementById('postcode').focus();\r\n");
      out.write("                	return false;\r\n");
      out.write("                }\r\n");
      out.write("                */\r\n");
      out.write("                \r\n");
      out.write("                /*\r\n");
      out.write("                // 도로명 주소\r\n");
      out.write("                regExp = /^[가-힣0-9]{3,}$/;\r\n");
      out.write("                var roadAddress = document.getElementById('roadAddress').value;\r\n");
      out.write("                if(!regExp.test(roadAddress)) {\r\n");
      out.write("                	alert(\"'도로명주소' 부분이 잘못되었습니다. 다시 입력해 주세요.\");\r\n");
      out.write("                	document.getElementById('roadAddress').focus();\r\n");
      out.write("                	return false;\r\n");
      out.write("                }\r\n");
      out.write("                */\r\n");
      out.write("                \r\n");
      out.write("                // 상세주소\r\n");
      out.write("                regExp = /^[가-힣0-9]{3,}$/;\r\n");
      out.write("                var detailAddress = document.getElementById('detailAddress').value;\r\n");
      out.write("                if(!regExp.test(detailAddress)) {\r\n");
      out.write("                	alert(\"'상세주소'' 부분이 잘못되었습니다. 다시 입력해 주세요.\");\r\n");
      out.write("                	document.getElementById('detailAddress').focus();\r\n");
      out.write("                	return false;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("				\r\n");
      out.write("                // 휴대전화번호\r\n");
      out.write("                regExp = /^[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]$/;\r\n");
      out.write("                var phone = document.getElementById('phone').value;\r\n");
      out.write("                \r\n");
      out.write("                if(!regExp.test(phone)) {\r\n");
      out.write("                    alert(\"휴대전화번호를 확인해 주세요.\");\r\n");
      out.write("                    document.getElementById('phone').focus();\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                 // 카드 번호\r\n");
      out.write("                regExp = /^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$/;\r\n");
      out.write("                var cardNum = document.getElementById('cardNum').value;\r\n");
      out.write("               \r\n");
      out.write("                if(!regExp.test(cardNum)) {\r\n");
      out.write("                    alert(\"카드 번호를 확인해 주세요.\");\r\n");
      out.write("                    document.getElementById('cardNum').focus();\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                // 카드 비밀번호\r\n");
      out.write("                regExp = /^\\d{4}$/\r\n");
      out.write("                var cardPwd = document.getElementById('cardPwd').value;\r\n");
      out.write("                if(!regExp.test(cardPwd)) {\r\n");
      out.write("                    alert(\"카드 비밀번호를 확인해 주세요.\");\r\n");
      out.write("                    document.getElementById('cardPwd').focus();\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("        <!-- 장바구니 삭제 및 주문버튼 클릭시 jQuery 끝 -->\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	    <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2021</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
